### ISSUE TITLE
Make the xml-dtd JAR available in Maven Central

### ISSUE THREAD

**Issue by vmassol** [css4j/xml-dtd#7]
Hi Carlos,

I know you're against it but right now we have a problem in XWiki. We can't really use a maven dependency to xml-dtd in XWiki Commons since we deploy XWiki Commons in Maven Central and one rule of Maven Central is to not have a dependency that is not in Maven Central. This led to the creation of https://jira.xwiki.org/browse/XCOMMONS-2094 and the rollback of https://jira.xwiki.org/browse/XCOMMONS-2025

Thus FTM, I don't have any solution except copying your code (`DefaultEntityResolver` and `AgentUtil`) inside the XWiki code base. I hope this is fine for you (I'll keep your license mentioned). The other solution would be to not use your code but that would be a pity.

Thanks

**Comment by carlosame** [comment]
Hi Vincent,

As I have [previously mentioned](https://groups.google.com/g/css4j/c/op5jIoINb3M/m/IiiN-LfkDAAJ) there is no way that I'm going to accept terms of use that have built-in [retroactivity](https://definitions.uslegal.com/r/retroactive/), and I'm puzzled at how other people do.

Please feel free to use the source code in the way that better serve your needs, according to the licence.

**Comment by vmassol** [comment]
> Please feel free to use the source code in the way that better serve your needs, according to the licence.

ok thanks. I'll try (just realized that I also need to copy all DTD and MOD files).

**Comment by carlosame** [comment]
I was unable to enter XCOMMONS-2561, so I put the comment here. Security scanners are more than likely to report false XXE positives on XWiki, due to the `http://apache.org/xml/features/nonvalidating/load-external-dtd` feature not being applied (about that feature: I wonder why XML parsers can't just apply a predefined self-provided HTML5 entity set like I do in my resolver).

You would be surprised at how many people (in big corporations) run a security scanner to evaluate a piece of software (as corporate security policy), then silently run away from it if the scanner reports something, without bothering to comment about that to the software developers. So my suggestion would be to put a warning in the XWiki documentation, in bold letters. Something like:

**WARNING: some security scanners may report known false positives when run on the XWiki codebase. For example, they may report a non-existent XXE vulnerability in XML processing. If you have any concern about the security of XWiki, please use the recommended channels to ask us.**

Related: github/codeql#7607

**Comment by vmassol** [comment]
Thanks for your comment @carlosame !

> Security scanners are more than likely to report false XXE positives on XWiki, due to the http://apache.org/xml/features/nonvalidating/load-external-dtd feature not being applied

Are you saying that XWiki doesn't set this feature explicitly and thus is somewhat protected?

For some context, I'm investigating potential XXE attacks reported by SonarQube. The one that got me to raise this issue is because I found out that an XWiki committer had reverted the use of xml-dtd's `DefaultEntityResolver` because when I committed the usage of it, I forgot that I was violating the Maven Central recommendation of not using dependencies not present on Maven Central. The revert actually did not cause a valid XXE attack but only because there was a bug with it that caused a NPE ;) Fixing that NPE would have opened the XXE attack. So I've re-applied the usage of xml-dtd, and verified that the XXE is no longer possible.

I'm not sure the warning would help much since not thorough testers would probably not even read it ;)

I'll see if SonarQube reports false positives XXE with the usage of xml-dtd's entity resolver (right now it doesn't).

Thanks, much appreciated!

**Comment by carlosame** [comment]
> > Security scanners are more than likely to report false XXE positives on XWiki, due to the http://apache.org/xml/features/nonvalidating/load-external-dtd feature not being applied
> 
> Are you saying that XWiki doesn't set this feature explicitly and thus is somewhat protected?

Security scanners tend to follow the [XXE OWASP recommendations](https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#java) and look for either the `http://apache.org/xml/features/disallow-doctype-decl` or `http://apache.org/xml/features/nonvalidating/load-external-dtd` being applied. If they aren't, they generally report a XXE vulnerability.

I haven't looked at your sources that use the `DefaultEntityResolver` but I assume that none of those are being applied, because otherwise there would be no point in using a resolver: it would never get called.

> I'm not sure the warning would help much since not thorough testers would probably not even read it ;)

Probably, that's up to you to decide. I had to warn and that's done :)

> I'll see if SonarQube reports false positives XXE with the usage of xml-dtd's entity resolver (right now it doesn't).

Maybe SonarQube is smarter than it used to be, or perhaps XWiki is using those configurations. In the latter case, you are not calling the resolver (and hence could lose entities).

For example, I see that `XMLUtils.parse()` is configuring `DISABLE_EXTERNAL_DOCTYPE_DECLARATION` and `DISABLE_DTD_PARAM` which are the features mentioned above:

https://github.com/xwiki/xwiki-commons/blob/e0e5a707366c66c34db691ca74b805909770d441/xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/XMLUtils.java#L582-L613

Haven't looked at what xwiki-platform does.

**Comment by carlosame** [comment]
I just noticed that there are a few potentially unsafe transforms in `XMLUtils`. [OWASP recommends this](https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#transformerfactory):

```java
TransformerFactory tf = TransformerFactory.newInstance();
tf.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "");
tf.setAttribute(XMLConstants.ACCESS_EXTERNAL_STYLESHEET, "");
```

although I'd use the following instead (because I'm not sure if your users need `ACCESS_EXTERNAL_STYLESHEET`, although also due to concerns about lost entities)

```java
TransformerFactory tf = TransformerFactory.newInstance();
tf.setAttribute(XMLConstants.FEATURE_SECURE_PROCESSING, true);
```

however the current XWiki-Commons code does neither (and it is strange that SonarQube isn't flagging those):

<br/>


1) Unconfigured `Transformer` in `extractXML`:

```java
handler = new ExtractHandler(start, length);
Transformer xformer = TransformerFactory.newInstance().newTransformer();
xformer.setErrorListener(RELAXED_ERROR_LISTENER);
xformer.transform(new DOMSource(node), new SAXResult(handler));
```

https://github.com/xwiki/xwiki-commons/blob/e0e5a707366c66c34db691ca74b805909770d441/xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/XMLUtils.java#L218-L221

2) Another one:

```java
javax.xml.transform.TransformerFactory.newInstance().newTransformer(xslt).transform(xml, result);`
```

in

https://github.com/xwiki/xwiki-commons/blob/e0e5a707366c66c34db691ca74b805909770d441/xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/XMLUtils.java#L673

3) `formatXMLContent` is safe but uses an empty resolver, which would lead to entities being lost:

```java
reader.setEntityResolver(new org.xml.sax.EntityResolver() {
    @Override
    public InputSource resolveEntity(String publicId, String systemId)
        throws SAXException, IOException
    {
        // Return an empty resolved entity. Note that we don't return null since this would tell the reader
        // to go on the internet to fetch the DTD.
        return new InputSource(new StringReader(""));
    }
});
```

https://github.com/xwiki/xwiki-commons/blob/e0e5a707366c66c34db691ca74b805909770d441/xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/XMLUtils.java#L706-L715

**Comment by vmassol** [comment]
@carlosame I'll check thanks. Yes, I have a few issues to look at already reported by SonarQube, see https://sonarcloud.io/project/issues?resolved=false&sonarsourceSecurity=xxe&id=org.xwiki.commons%3Axwiki-commons

**Comment by vmassol** [comment]
> I just noticed that there are a few potentially unsafe transforms in XMLUtils. [OWASP recommends this](https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#transformerfactory):

> ```
> TransformerFactory tf = TransformerFactory.newInstance();
> tf.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "");
> tf.setAttribute(XMLConstants.ACCESS_EXTERNAL_STYLESHEET, "");
> ```

We're using Apache Xerces and AFAIK, it's the same or better to use the `http://apache.org/xml/features/disallow-doctype-decl` feature. For example: https://github.com/xwiki/xwiki-platform/commit/61081ec17eb093bab1cec517dcb16f83a020f403

> Unconfigured Transformer in extractXML:

Reported at https://sonarcloud.io/project/issues?resolved=false&sonarsourceSecurity=xxe&id=org.xwiki.commons%3Axwiki-commons&open=AXDOBFn83-iMCxIZIEYl

> `javax.xml.transform.TransformerFactory.newInstance().newTransformer(xslt).transform(xml, result);`

Reported at https://sonarcloud.io/project/issues?resolved=false&sonarsourceSecurity=xxe&id=org.xwiki.commons%3Axwiki-commons&open=AXDOBFn83-iMCxIZIEYk

> formatXMLContent is safe but uses an empty resolver, which would lead to entities being lost:

I'll fix this one, thanks.

There's one more: https://sonarcloud.io/project/issues?resolved=false&sonarsourceSecurity=xxe&id=org.xwiki.commons%3Axwiki-commons&open=AXDOBFn83-iMCxIZIEYm

**Comment by vmassol** [comment]
> We're using Apache Xerces and AFAIK, it's the same or better to use the http://apache.org/xml/features/disallow-doctype-decl feature. For example: https://github.com/xwiki/xwiki-platform/commit/61081ec17eb093bab1cec517dcb16f83a020f403

I guess it depends on the use case and whether entities are allowed or not.

**Comment by vmassol** [comment]
At https://blog.sonarsource.com/secure-xml-processor/ for example, it says:

> By default FSP is partially enabled and prevents XML denial of service attacks. However, it is only when FSP is explicitly fully enabled, by calling the setFeature method to set the FSP property to true, that [external connections are also expected to be disallowed](https://docs.oracle.com/en/java/javase/13/security/java-api-xml-processing-jaxp-security-guide.html#GUID-94ABC0EE-9DC8-44F0-84AD-47ADD5340477). Unfortunately it’s not the case for all XML processors, for instance on Apache Xerces, FSP doesn’t restrict external connections and thus doesn’t protect against XXE vulnerabilities.
>
> Therefore, be sure to test FSP behavior with regard to XXE vulnerabilities and use additional properties, such as the others we present in this post, to explicitly and directly disable or restrict XXEs.

Now I'm not sure if this is true. In my simple XXE test, using `tf.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);` was enough to prevent file access for ex.

**Comment by vmassol** [comment]
Hi @carlosame 

> BTW [http://apache.org/xml/features/disallow-doctype-decl](https://xerces.apache.org/xerces2-j/features.html#disallow-doctype-decl) blows the parsing (fatal error) if any DOCTYPE is present. Not good backwards-compatibility vibes for XWiki users that are just upgrading their versions...

Yes this is true. I've used it in places where the XML files are not supposed to contain DTDs.

However, I'd like in the future to refactor all XML parsing operations in XWiki to use your custom entity resolver.

> You are still vulnerable to jar decompression bombs and SSRF problems (which can be fixed with my resolver). 

I've tried the following unit test to try an XML Bomb (found at https://vulncat.fortify.com/en/detail?id=desc.controlflow.dotnet.xml_entity_expansion_injection), and it seems the JDK is protected by default (Java 11):

```
    @Test
    void transformAvoidXMLBomb()
    {
        String xml = "<?xml version=\"1.0\"?>\n"
            + "<!DOCTYPE lolz [\n"
            + "  <!ENTITY lol \"lol\">\n"
            + "  <!ENTITY lol2 \"&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;\">\n"
            + "  <!ENTITY lol3 \"&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;\">\n"
            + "  <!ENTITY lol4 \"&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;\">\n"
            + "  <!ENTITY lol5 \"&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;\">\n"
            + "  <!ENTITY lol6 \"&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;\">\n"
            + "  <!ENTITY lol7 \"&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;\">\n"
            + "  <!ENTITY lol8 \"&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;\">\n"
            + "  <!ENTITY lol9 \"&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;\">\n"
            + "]>\n"
            + "<lolz>&lol9;</lolz>";
        String xslt = "<xsl:stylesheet version=\"1.0\" xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\">\n"
            + "<xsl:output method=\"text\"/>\n"
            + "</xsl:stylesheet>";

        assertNotNull(XMLUtils.transform(new StreamSource(
            new ByteArrayInputStream(xml.getBytes())), new StreamSource(new ByteArrayInputStream(xslt.getBytes()))));
    }
```

I get:

```
ERROR:  'JAXP00010001: The parser has encountered more than "64000" entity expansions in this document; this is the limit imposed by the JDK.'
ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: JAXP00010001: The parser has encountered more than "64000" entity expansions in this document; this is the limit imposed by the JDK.'
```

Note that I get this even if I don't set the `FEATURE_SECURE_PROCESSING` feature.

About XXE SSRF attacks, the `FEATURE_SECURE_PROCESSING` feature seems to blocks all scheme access to remote DTDs (I've tried with `http`, `https` and `ftp` and they were all blocked).

Last, the https://en.wikipedia.org/wiki/Billion_laughs_attack attack is blocked too (see above - I'm just realizing that my XML bomb example is actually the billion laughs attack ;)).

So it seems that the `FEATURE_SECURE_PROCESSING` feature is actually protecting from all. The only problem is what ou said: using this feature will prevent well-known entities from working, which would work with your entity resolver.

Now I'm not sure how to convert the following code to use your entity resolver:

```
    public static String transform(Source xml, Source xslt)
    {
        if (xml != null && xslt != null) {
            try {
                StringWriter output = new StringWriter();
                Result result = new StreamResult(output);
                XMLUtils.createTransformerFactory().newTransformer(xslt).transform(xml, result);
                return output.toString();
            } catch (Exception ex) {
                LOGGER.warn("Failed to apply XSLT transformation: [{}]", ex.getMessage());
            }
        }
        return null;
    }
...
    private static TransformerFactory createTransformerFactory() throws TransformerConfigurationException
    {
        TransformerFactory tf = TransformerFactory.newInstance();
        tf.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
        return tf;
    }
```

I don't see how to set a custom entity resolver for reading the XML source. I know that using a `SAXSource` allows to do so (since that's what I see done at https://github.com/xwiki/xwiki-commons/blob/b054f2257f93e0acf535a339a089fddcfd049e92/xwiki-commons-core/xwiki-commons-xml/src/main/java/org/xwiki/xml/XMLUtils.java#L703-L718 ) but since a `Source` is passed and the code doesn't control it, I don't see what do. I'm mentioning it in case you have an idea :)

Thanks again!

**Comment by vmassol** [comment]
To answer my question, indeed, a, `XMLReader` can only be specified when using a `SAXSource`. See this code from `DTMManagerDefault` in the JDK: 

```
  synchronized public XMLReader getXMLReader(Source inputSource)
  {

    try
    {
      XMLReader reader = (inputSource instanceof SAXSource)
                         ? ((SAXSource) inputSource).getXMLReader() : null;

      // If user did not supply a reader, ask for one from the reader manager
      if (null == reader) {
        if (m_readerManager == null) {
            m_readerManager = XMLReaderManager.getInstance(super.overrideDefaultParser());
        }

        reader = m_readerManager.getXMLReader();
      }

      return reader;

    } catch (SAXException se) {
      throw new DTMException(se.getMessage(), se);
    }
  }
```

**Comment by vmassol** [comment]
About:

> // Note: the following line should not be needed with the custom entity resolver used
> // spf.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);

Actually it is needed to protect against XML bombs! Without it, it hangs. So it seems that your Entity Resolver doesn't protect against XML bombs. Could you confirm? Thx!

**Comment by carlosame** [comment]
> About:
> 
> > // Note: the following line should not be needed with the custom entity resolver used
> > // spf.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
> 
> Actually it is needed to protect against XML bombs! Without it, it hangs. So it seems that your Entity Resolver doesn't protect against XML bombs. Could you confirm? Thx!

I never claimed that the resolver is effective against entity expansion attacks (what you call XML bombs), quite the opposite, please read the Javadoc carefully.

What I claim is that it is effective against **jar decompression bombs** which are a different threat (and more dangerous IMO). Imagine the following DTD:

```dtd
<!DOCTYPE doc PUBLIC "-//W3C//DTD FOO 1.0//EN" "jar:http://www.example.com/evil.jar!/file.dtd">
```
You do not want that System ID to be used, and the resolver prevents that.

**Comment by vmassol** [comment]
> I never claimed that the resolver is effective against entity expansion attacks (what you call XML bombs), quite the opposite, please read the Javadoc carefully.
>
> What I claim is that it is effective against jar decompression bombs which are a different threat (and more dangerous IMO). Imagine the following DTD:

ok my bad, I thought they were the same. I had a hard time to understand the link from your javadoc to https://en.wikipedia.org/wiki/Zip_bomb and how it relates to XML parsing, so I thought you meant an XML Bomb by similarity.

Thanks for the clarification!

**Comment by carlosame** [comment]
> About:
> 
> > `<!DOCTYPE doc PUBLIC "-//W3C//DTD FOO 1.0//EN" "jar:http://www.example.com/evil.jar!/file.dtd">`
> 
> I've tested this with just the `FEATURE_SECURE_PROCESSING` feature set and it seems I'm protected since I get:
> 
> ```
> ERROR:  'External DTD: Failed to read external DTD 'file.dtd', because 'http' access is not allowed due to restriction set by the accessExternalDTD property.'
> ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: External DTD: Failed to read external DTD 'file.dtd', because 'http' access is not allowed due to restriction set by the accessExternalDTD property.'
> ```

This is due to the `http://javax.xml.XMLConstants/property/accessExternalDTD` that I mentioned in an earlier reply. IIRC `accessExternalDTD` is not enforced if you use a resolver that returns `null`, so in the end you need a resolver like mine if you want entities AND being safe.

I'd suggest that you create a set of three entity-preservation tests for any of the places where XML parser and Transformers are created in XWiki:

1) Entities are replaced in a document with a DTD that has both Public and System ID, like:

```xml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
```

2) The DTD has no Public nor System IDs:
```xml
<!DOCTYPE html>
```

3) No DTD at all, but entities keep being replaced (entity mapping provided as external subset). This requires an XML parser that supports `EntityResolver2` (all the widely used parsers do).

What about moving all of this to a separate discussion?

**Comment by carlosame** [comment]
Please see #10 :)
